name: Build, Test, Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, build, test
        run: |
          npm install
          npm run build --if-present
          npm run web
          npm run test
      - name: publish github release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ github.token }}
